namespace Kawai.Domain.DTOs;

public class ItemDto : DataTableDto
{
    public string ItemCode { get; set; }
    public string ItemName { get; set; }
    public string FinishGoodPartCls { get; set; }
    public string FinishGoodPartClsDesc { get; set; }
    public string DrawingNumber { get; set; }
    public string WarehouseCode { get; set; }
    public string WarehouseName { get; set; }
    public string Address { get; set; }
    public string SupplierCode { get; set; }
    public string SupplierName { get; set; }
    public string DeliveryPlaceCode { get; set; }
    public string DeliveryPlaceName { get; set; }
    public string ManufactureCode { get; set; }
    public string ManufactureName { get; set; }
    public string LineCode { get; set; }
    public string LineName { get; set; }
    public string MakerItemCode { get; set; }
    public string MakerItemName { get; set; }
    public string PartCls { get; set; }
    public string PartClsDesc { get; set; }
    public string ReserveCls { get; set; }
    public string ReserveClsDesc { get; set; }
    public string SupplyCls { get; set; }
    public string SupplyClsDesc { get; set; }
    public string ProvisionCls { get; set; }
    public string ProvisionClsDesc { get; set; }
    public string ProductionCls { get; set; }
    public string ProductionClsDesc { get; set; }
    public string MaterialCls { get; set; }
    public string MaterialClsDesc { get; set; }
    public decimal? Thickness { get; set; }
    public decimal? Width { get; set; }
    public decimal? Length { get; set; }
    public decimal? Weight { get; set; }
    public decimal? GrossWeight { get; set; }
    public string SheetCoilCls { get; set; }
    public string SheetCoilClsDesc { get; set; }
    public decimal? Pitch { get; set; }
    public decimal? NumberProducible { get; set; }
    public decimal? ScrapWeight { get; set; }
    public string DrawingMaterialCls { get; set; }
    public string DrawingMaterialClsDesc { get; set; }

    public string SurfaceTreatmentCls { get; set; }
    public string SurfaceTreatmentClsDesc { get; set; }
    public decimal? SurfaceOrderPointQty { get; set; }
    public string HeatTreatmentCls { get; set; }
    public string HeatTreatmentClsDesc { get; set; }
    public decimal? HeatOrderPointQty { get; set; }
    public decimal? Sample { get; set; }
    public decimal? SWQty { get; set; }
    public decimal? EWQty { get; set; }
    public decimal? NumberProcess { get; set; }
    public decimal? MaterialCoefficient { get; set; }
    public decimal? ProcessCoefficient { get; set; }
    public decimal? MinLot { get; set; }
    public decimal? LotQty { get; set; }
    public decimal? LotCoefficience { get; set; }
    public decimal? ProductReadTime { get; set; }
    public decimal? YieldPercentage { get; set; }
    public decimal? NumberEntering { get; set; }
    public string PackingStyleCls { get; set; }
    public string PackingStyleClsDesc { get; set; }
    public string GroupCls { get; set; }
    public string GroupClsDesc { get; set; }
    public decimal? StandardStock { get; set; }
    public decimal? SafetyStock { get; set; }
    public decimal? MaxStock { get; set; }
    public decimal? MinStock { get; set; }
    public decimal? AlowanceDay { get; set; }
    public decimal? DeliveryReadTime { get; set; }
    public string MakeBuyCls { get; set; }
    public string MakeBuyClsDesc { get; set; }
    public string ControlCls { get; set; }
    public string ControlClsDesc { get; set; }
    public string ColorCls { get; set; }
    public string ColorClsDesc { get; set; }
    public string DestinationCls { get; set; }
    public string DestinationClsDesc { get; set; }
    public decimal? OrderPointQty { get; set; }
    public string UnitCls { get; set; }
    public string UnitClsDesc { get; set; }
    public decimal NumberBox { get; set; }
    public string PackingStyleMaterialCls { get; set; }
    public string PackingStyleMaterialClsDesc { get; set; }
    public string AccountingCode { get; set; }
    public string ExplosionCls { get; set; }
    public string ExplosionClsDesc { get; set; }
    public string PersonInChargeCls { get; set; }
    public string PersonInChargeClsDesc { get; set; }
    public string StockControlCls { get; set; }
    public string StockControlClsDesc { get; set; }
    public string SupplyIssueCls { get; set; }
    public string SupplyIssueClsDesc { get; set; }
    public DateTime? UseEndDay { get; set; }
    public string HSCode { get; set; }
    public string HSName { get; set; }
    public decimal MinOrder { get; set; }
    public decimal SafetyStockPercentage { get; set; }
    public string SAPItemCode { get; set; }
    public string TypeAccs { get; set; }
    public string ModelCls { get; set; }
    public string ModelClsDesc { get; set; }
    public string POTypeCls { get; set; }
    public string POTypeClsDesc { get; set; }
    public string ClasificationPartCls { get; set; }
    public string ClasificationPartClsDesc { get; set; }

    public DateTime? LastUpdate { get; set; }
    public string LastUser { get; set; }
    public DateTime RegisterDate { get; set; }
    public string DDLDescription { get; set; }
}
