namespace Kawai.Domain.DTOs;

public class ItemDto : DataTableDto
{
    public string ItemCode { get; set; }
    public string ItemName { get; set; }
    public string FinishGoodPartCls { get; set; }
    public string FinishGoodPartClsDesc { get; set; }
    public string DrawingNumber { get; set; }
    public string WarehouseCode { get; set; }
    public string WarehouseName { get; set; }
    public string Address { get; set; }
    public string SupplierCode { get; set; }
    public string SupplierName { get; set; }
    public string DeliveryPlaceCode { get; set; }
    public string DeliveryPlaceName { get; set; }
    public string ManufactureCode { get; set; }
    public string ManufactureName { get; set; }
    public string LineCode { get; set; }
    public string LineName { get; set; }
    public string MakerItemCode { get; set; }
    public string MakerItemName { get; set; }
    public string PartCls { get; set; }
    public string PartClsDesc { get; set; }
    public bool ReserveCls { get; set; }
    public string ReserveClsDesc { get; set; }
    public bool SupplyCls { get; set; }
    public string SupplyClsDesc { get; set; }
    public bool ProvisionCls { get; set; }
    public string ProvisionClsDesc { get; set; }
    public bool ProductionCls { get; set; }
    public string ProductionClsDesc { get; set; }
    public string MaterialCls { get; set; }
    public string MaterialClsDesc { get; set; }
    public double? Thickness { get; set; }
    public double? Width { get; set; }
    public double? Length { get; set; }
    public double? Weight { get; set; }
    public double? GrossWeight { get; set; }
    public string SheetCoilCls { get; set; }
    public string SheetCoilClsDesc { get; set; }
    public double? Pitch { get; set; }
    public double? NumberProducible { get; set; }
    public double? ScrapWeight { get; set; }
    public string DrawingMaterialCls { get; set; }
    public string DrawingMaterialClsDesc { get; set; }

    public string SurfaceTreatmentCls { get; set; }
    public string SurfaceTreatmentClsDesc { get; set; }
    public double? SurfaceOrderPointQty { get; set; }
    public string HeatTreatmentCls { get; set; }
    public string HeatTreatmentClsDesc { get; set; }
    public double? HeatOrderPointQty { get; set; }
    public double? Sample { get; set; }
    public double? SWQty { get; set; }
    public double? EWQty { get; set; }
    public double? NumberProcess { get; set; }
    public double? MaterialCoefficient { get; set; }
    public double? ProcessCoefficient { get; set; }
    public double? MinLot { get; set; }
    public double? LotQty { get; set; }
    public double? LotCoefficience { get; set; }
    public double? ProductReadTime { get; set; }
    public double? YieldPercentage { get; set; }
    public double? NumberEntering { get; set; }
    public string PackingStyleCls { get; set; }
    public string PackingStyleClsDesc { get; set; }
    public string GroupCls { get; set; }
    public string GroupClsDesc { get; set; }
    public double? StandardStock { get; set; }
    public double? SafetyStock { get; set; }
    public double? MaxStock { get; set; }
    public double? MinStock { get; set; }
    public double? AlowanceDay { get; set; }
    public double? DeliveryReadTime { get; set; }
    public string MakeBuyCls { get; set; }
    public string MakeBuyClsDesc { get; set; }
    public string ControlCls { get; set; }
    public string ControlClsDesc { get; set; }
    public string ColorCls { get; set; }
    public string ColorClsDesc { get; set; }
    public string DestinationCls { get; set; }
    public string DestinationClsDesc { get; set; }
    public double? OrderPointQty { get; set; }
    public string UnitCls { get; set; }
    public string UnitClsDesc { get; set; }
    public double NumberBox { get; set; }
    public string PackingStyleMaterialCls { get; set; }
    public string PackingStyleMaterialClsDesc { get; set; }
    public string AccountingCode { get; set; }
    public string ExplosionCls { get; set; }
    public string ExplosionClsDesc { get; set; }
    public string PersonInChargeCls { get; set; }
    public string PersonInChargeClsDesc { get; set; }
    public string StockControlCls { get; set; }
    public string StockControlClsDesc { get; set; }
    public string SupplyIssueCls { get; set; }
    public string SupplyIssueClsDesc { get; set; }
    public DateTime? UseEndDay { get; set; }
    public string HSCode { get; set; }
    public string HSName { get; set; }
    public double MinOrder { get; set; }
    public double SafetyStockPercentage { get; set; }
    public string SAPItemCode { get; set; }
    public string TypeAccs { get; set; }
    public string ModelCls { get; set; }
    public string ModelClsDesc { get; set; }
    public string POTypeCls { get; set; }
    public string POTypeClsDesc { get; set; }
    public string ClasificationPartCls { get; set; }
    public string ClasificationPartClsDesc { get; set; }

    public DateTime? LastUpdate { get; set; }
    public string LastUser { get; set; }
    public DateTime RegisterDate { get; set; }
}
