SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_TPB_Bahan_Baku](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CIF] [decimal](38, 2) NULL,
	[CIF_RUPIAH] [decimal](38, 2) NULL,
	[HARGA_PENYERAHAN] [decimal](38, 2) NULL,
	[HARGA_PEROLEHAN] [decimal](38, 2) NULL,
	[JENIS_SATUAN] [varchar](255) NULL,
	[JUMLAH_SATUAN] [decimal](38, 4) NULL,
	[KODE_ASAL_BAHAN_BAKU] [int] NULL,
	[KODE_BARANG] [varchar](255) NULL,
	[KODE_FASILITAS_DOKUMEN] [varchar](255) NULL,
	[KODE_JENIS_DOK_ASAL] [varchar](255) NULL,
	[KODE_KANTOR] [varchar](255) NULL,
	[KODE_SKEMA_TARIF] [varchar](255) NULL,
	[KODE_STATUS] [varchar](255) NULL,
	[MERK] [varchar](255) NULL,
	[NDPBM] [decimal](38, 4) NULL,
	[NETTO] [decimal](38, 4) NULL,
	[NOMOR_AJU_DOK_ASAL] [varchar](255) NULL,
	[NOMOR_DAFTAR_DOK_ASAL] [varchar](255) NULL,
	[POS_TARIF] [varchar](255) NULL,
	[SERI_BAHAN_BAKU] [int] NULL,
	[SERI_BARANG] [int] NULL,
	[SERI_IJIN] [int] NULL,
	[SERI_BARANG_DOK_ASAL] [int] NULL,
	[SPESIFIKASI_LAIN] [varchar](255) NULL,
	[TANGGAL_DAFTAR_DOK_ASAL] [datetime] NULL,
	[TIPE] [varchar](255) NULL,
	[UKURAN] [varchar](255) NULL,
	[URAIAN] [varchar](255) NULL,
	[ID_BARANG] [int] NULL,
	[ID_HEADER] [int] NULL,
	[NO_PENGAJUAN] [varchar](50) NULL,
 CONSTRAINT [PK__Bea_Cuka__3214EC27186E5E3A] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
