SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Pelabuhan](
	[ID] [int] NOT NULL,
	[KETERANGAN] [varchar](255) NULL,
	[KODE_KANTOR] [varchar](255) NULL,
	[KODE_PELABUHAN] [varchar](255) NULL,
	[URAIAN_PELABUHAN] [varchar](255) NULL
) ON [PRIMARY]
GO
