SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[JENIS_TARIF] [varchar](255) NULL,
	[JUMLAH_SATUAN] [decimal](38, 4) NULL,
	[KODE_ASAL_BAHAN_BAKU] [int] NULL,
	[KODE_FASILITAS] [varchar](255) NULL,
	[KODE_KOMODITI_CUKAI] [varchar](255) NULL,
	[KODE_SATUAN] [varchar](255) NULL,
	[KODE_TARIF] [varchar](255) NULL,
	[NILAI_BAYAR] [decimal](38, 2) NULL,
	[NILAI_FASILITAS] [decimal](38, 2) NULL,
	[NILAI_SUDAH_DILUNASI] [decimal](38, 2) NULL,
	[SERI_BAHAN_BAKU] [int] NULL,
	[SERI_BARANG] [int] NULL,
	[TARIF] [decimal](38, 2) NULL,
	[TARIF_FASILITAS] [decimal](38, 2) NULL,
	[ID_BAHAN_BAKU] [int] NULL,
	[ID_BARANG] [int] NULL,
	[ID_HEADER] [int] NULL,
	[NO_PENGAJUAN] [varchar](50) NULL,
 CONSTRAINT [PK__Bea_Cuka__3214EC278A2298A8] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
