SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai25_Doc](
	[No_Pengajuan] [varchar](50) NULL,
	[SuratJalan_No] [varchar](25) NOT NULL,
	[Pengajuan_Date] [datetime] NULL,
	[Interface_Cls] [char](1) NULL,
 CONSTRAINT [PK_Bea_CUkai25_Doc] PRIMARY KEY CLUSTERED 
(
	[SuratJalan_No] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
