SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Jenis_Tarif](
	[ID] [int] NULL,
	[KODE_JENIS_TARIF] [varchar](255) NULL,
	[URAIAN_JENIS_TARIF] [varchar](255) NULL
) ON [PRIMARY]
GO
