SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SS_UserMobilePrivilege](
	[UserID] [varchar](30) NOT NULL,
	[MenuID] [varchar](10) NOT NULL,
	[AllowAccess] [bit] NULL,
 CONSTRAINT [PK_SS_UserMobilePrivilege] PRIMARY KEY CLUSTERED 
(
	[MenuID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
