SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MRP_Setting](
	[MRP_Year] [char](4) NOT NULL,
	[MRP_Month] [char](2) NOT NULL,
	[Calc_F] [char](1) NULL,
	[Calc_O] [char](1) NULL,
	[Calc_D] [char](1) NULL,
	[Last_Update] [datetime] NULL,
	[Last_User] [char](15) NULL,
	[Register_Date] [datetime] NULL,
 CONSTRAINT [PK_MRP_Setting] PRIMARY KEY CLUSTERED 
(
	[MRP_Year] ASC,
	[MRP_Month] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
