SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [BC_Master](
	[Bc_Type] [varchar](15) NOT NULL,
	[Description] [varchar](25) NULL,
	[Last_User] [varchar](15) NULL,
	[Last_Update] [datetime] NULL,
 CONSTRAINT [PK_BC_Master] PRIMARY KEY CLUSTERED 
(
	[Bc_Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
