SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MS_NG](
	[NGCode] [varchar](25) NOT NULL,
	[Description] [nvarchar](200) NULL,
	[Lastuser] [varchar](50) NULL,
	[LastUpdate] [datetime] NULL,
	[IsCommon] [bit] NOT NULL,
 CONSTRAINT [PK_MS_NG] PRIMARY KEY CLUSTERED 
(
	[NGCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
