SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Tarif_Fasilitas](
	[ID] [int] NOT NULL,
	[KODE_DOKUMEN_PABEAN] [varchar](255) NULL,
	[KODE_FASILITAS] [varchar](255) NULL,
	[URAIAN_FASILITAS] [varchar](255) NULL,
	[URAIAN_PENDEK] [varchar](255) NULL
) ON [PRIMARY]
GO
