SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Kategori_Barang](
	[ID] [int] NOT NULL,
	[KODE_KATEGORI] [varchar](255) NULL,
	[KODE_TUJUAN_TPB] [varchar](255) NULL,
	[URAIAN_KATEGORI] [varchar](255) NULL
) ON [PRIMARY]
GO
