SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Color_Cls](
	[Color_Cls] [varchar](2) NOT NULL,
	[Description] [varchar](50) NULL,
	[Last_Update] [datetime] NULL,
	[Last_User] [varchar](15) NULL,
	[Register_Date] [datetime] NULL,
 CONSTRAINT [PK_Color_Cls] PRIMARY KEY CLUSTERED 
(
	[Color_Cls] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Color_Cls] ADD  CONSTRAINT [DF_Color_Cls_Register_Date]  DEFAULT (getdate()) FOR [Register_Date]
GO
