SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TR_Cls](
	[TR_Id] [int] NOT NULL,
	[TR_Type] [char](2) NULL,
	[TR_TypeDesc] [char](25) NULL,
	[TR_Code] [char](2) NULL,
	[TR_CodeDesc] [char](25) NULL,
 CONSTRAINT [PK_TR_Cls] PRIMARY KEY CLUSTERED 
(
	[TR_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
