SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SS_UserAreaPrivilege](
	[UserID] [varchar](50) NOT NULL,
	[AreaCode] [varchar](25) NOT NULL,
	[AllowAccess] [bit] NULL,
	[Last_User] [char](15) NULL,
	[Last_Update] [datetime] NULL,
 CONSTRAINT [PK_SS_UserAreaPrivilege] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[AreaCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
