SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [IQC_Summary](
	[SummaryID] [int] IDENTITY(1,1) NOT NULL,
	[SupplierID] [int] NOT NULL,
	[Month] [varchar](10) NULL,
	[TotalLot] [int] NULL,
	[AcceptedLot] [int] NULL,
	[RejectedLot] [int] NULL,
	[RejectRate] [decimal](5, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[SummaryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [IQC_Summary] ADD  DEFAULT ((0)) FOR [TotalLot]
GO
ALTER TABLE [IQC_Summary] ADD  DEFAULT ((0)) FOR [AcceptedLot]
GO
ALTER TABLE [IQC_Summary] ADD  DEFAULT ((0)) FOR [RejectedLot]
GO
ALTER TABLE [IQC_Summary] ADD  DEFAULT ((0.00)) FOR [RejectRate]
GO
