SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Tujuan](
	[Kode_Tujuan] [int] NOT NULL,
	[Nama_Tujuan] [text] NULL,
 CONSTRAINT [PK_Bea_Cukai_Tujuan_1] PRIMARY KEY CLUSTERED 
(
	[Kode_Tujuan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
