SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Fasilitas](
	[ID] [int] NULL,
	[KODE_FASILITAS] [varchar](255) NULL,
	[URAIAN_FASILITAS] [varchar](255) NULL
) ON [PRIMARY]
GO
