SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_TPB_Bahan_Baku](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CIF] [decimal](38, 2) NULL,
	[CIF_RUPIAH] [decimal](38, 2) NULL,
	[HARGA_PENYERAHAN] [decimal](38, 2) NULL,
	[HARGA_PEROLEHAN] [decimal](38, 2) NULL,
	[JENIS_SATUAN] [varchar](255) NULL,
	[JUMLAH_SATUAN] [decimal](38, 4) NULL,
	[KODE_ASAL_BAHAN_BAKU] [int] NULL,
	[KODE_BARANG] [varchar](255) NULL,
	[KODE_FASILITAS_DOKUMEN] [varchar](255) NULL,
	[KODE_JENIS_DOK_ASAL] [varchar](255) NULL,
	[KODE_KANTOR] [varchar](255) NULL,
	[KODE_SKEMA_TARIF] [varchar](255) NULL,
	[KODE_STATUS] [varchar](255) NULL,
	[MERK] [varchar](255) NULL,
	[NDPBM] [decimal](38, 4) NULL,
	[NETTO] [decimal](38, 4) NULL,
	[NOMOR_AJU_DOK_ASAL] [varchar](255) NULL,
	[NOMOR_DAFTAR_DOK_ASAL] [varchar](255) NULL,
	[POS_TARIF] [varchar](255) NULL,
	[SERI_BAHAN_BAKU] [int] NULL,
	[SERI_BARANG] [int] NULL,
	[SERI_IJIN] [int] NULL,
	[SERI_BARANG_DOK_ASAL] [int] NULL,
	[SPESIFIKASI_LAIN] [varchar](255) NULL,
	[TANGGAL_DAFTAR_DOK_ASAL] [datetime] NULL,
	[TIPE] [varchar](255) NULL,
	[UKURAN] [varchar](255) NULL,
	[URAIAN] [varchar](255) NULL,
	[ID_BARANG] [int] NULL,
	[ID_HEADER] [int] NULL,
	[NO_PENGAJUAN] [varchar](50) NULL,
 CONSTRAINT [PK__Bea_Cuka__3214EC27186E5E3A] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai_T__CIF__0B840354]  DEFAULT (NULL) FOR [CIF]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__CIF_R__0C78278D]  DEFAULT (NULL) FOR [CIF_RUPIAH]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__HARGA__0D6C4BC6]  DEFAULT (NULL) FOR [HARGA_PENYERAHAN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__HARGA__0E606FFF]  DEFAULT (NULL) FOR [HARGA_PEROLEHAN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__JENIS__0F549438]  DEFAULT (NULL) FOR [JENIS_SATUAN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__JUMLA__1048B871]  DEFAULT (NULL) FOR [JUMLAH_SATUAN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___113CDCAA]  DEFAULT (NULL) FOR [KODE_ASAL_BAHAN_BAKU]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___123100E3]  DEFAULT (NULL) FOR [KODE_BARANG]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___1325251C]  DEFAULT (NULL) FOR [KODE_FASILITAS_DOKUMEN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___14194955]  DEFAULT (NULL) FOR [KODE_JENIS_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___150D6D8E]  DEFAULT (NULL) FOR [KODE_KANTOR]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___160191C7]  DEFAULT (NULL) FOR [KODE_SKEMA_TARIF]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___16F5B600]  DEFAULT (NULL) FOR [KODE_STATUS]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai___MERK__17E9DA39]  DEFAULT (NULL) FOR [MERK]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__NDPBM__18DDFE72]  DEFAULT (NULL) FOR [NDPBM]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__NETTO__19D222AB]  DEFAULT (NULL) FOR [NETTO]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__NOMOR__1AC646E4]  DEFAULT (NULL) FOR [NOMOR_AJU_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__NOMOR__1BBA6B1D]  DEFAULT (NULL) FOR [NOMOR_DAFTAR_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__POS_T__1CAE8F56]  DEFAULT (NULL) FOR [POS_TARIF]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__SERI___1DA2B38F]  DEFAULT (NULL) FOR [SERI_BAHAN_BAKU]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__SERI___1E96D7C8]  DEFAULT (NULL) FOR [SERI_BARANG]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__SERI___1F8AFC01]  DEFAULT (NULL) FOR [SERI_IJIN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__SERI___207F203A]  DEFAULT (NULL) FOR [SERI_BARANG_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__SPESI__21734473]  DEFAULT (NULL) FOR [SPESIFIKASI_LAIN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__TANGG__226768AC]  DEFAULT (NULL) FOR [TANGGAL_DAFTAR_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai___TIPE__235B8CE5]  DEFAULT (NULL) FOR [TIPE]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__UKURA__244FB11E]  DEFAULT (NULL) FOR [UKURAN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__URAIA__2543D557]  DEFAULT (NULL) FOR [URAIAN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__ID_BA__2637F990]  DEFAULT (NULL) FOR [ID_BARANG]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku] ADD  CONSTRAINT [DF__Bea_Cukai__ID_HE__272C1DC9]  DEFAULT (NULL) FOR [ID_HEADER]
GO
