SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Ukuran_Kontainer](
	[ID] [int] NOT NULL,
	[KODE_UKURAN_KONTAINER] [varchar](255) NULL,
	[URAIAN_UKURAN_KONTAINER] [varchar](255) NULL
) ON [PRIMARY]
GO
