SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_TPB_Bahan_Baku_Dokumen](
	[ID] [int] NULL,
	[KODE_ASAL_BAHAN_BAKU] [int] NULL,
	[SERI_DOKUMEN] [int] NULL,
	[ID_BAHAN_BAKU] [int] NULL,
	[ID_BARANG] [int] NULL,
	[ID_HEADER] [int] NULL,
	[SERI_BAHAN_BAKU] [int] NULL,
	[SERI_BARANG] [int] NULL,
	[NO_PENGAJUAN] [varchar](50) NULL
) ON [PRIMARY]
GO
