SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Pungutan](
	[ID] [int] NOT NULL,
	[KODE_PUNGUTAN] [varchar](255) NULL,
	[URAIAN_PUNGUTAN] [varchar](255) NULL
) ON [PRIMARY]
GO
