SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Kondisi_Barang](
	[ID] [int] NOT NULL,
	[KODE_KONDISI] [varchar](255) NULL,
	[URAIAN_KONDISI] [varchar](255) NULL
) ON [PRIMARY]
GO
