SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [AR_Master](
	[Cust_Code] [char](15) NOT NULL,
	[AR_No] [char](12) NOT NULL,
	[AR_Date] [datetime] NULL,
	[Last_Update] [datetime] NULL,
	[Last_User] [char](15) NULL,
	[Register_Date] [datetime] NULL,
 CONSTRAINT [PK_AR_Master] PRIMARY KEY CLUSTERED 
(
	[AR_No] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [AR_Master]  WITH NOCHECK ADD  CONSTRAINT [FK_AR_Master_Trade_Master] FOREIGN KEY([Cust_Code])
REFERENCES [Trade_Master] ([Trade_Code])
GO
ALTER TABLE [AR_Master] CHECK CONSTRAINT [FK_AR_Master_Trade_Master]
GO
