SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Bahan_Baku](
	[ID] [int] NOT NULL,
	[CIF] [decimal](38, 2) NULL,
	[CIF_RUPIAH] [decimal](38, 2) NULL,
	[HARGA_PENYERAHAN] [decimal](38, 2) NULL,
	[HARGA_PEROLEHAN] [decimal](38, 2) NULL,
	[JENIS_SATUAN] [varchar](255) NULL,
	[JUMLAH_SATUAN] [decimal](38, 4) NULL,
	[KODE_ASAL_BAHAN_BAKU] [int] NULL,
	[KODE_BARANG] [varchar](255) NULL,
	[KODE_FASILITAS_DOKUMEN] [varchar](255) NULL,
	[KODE_JENIS_DOK_ASAL] [varchar](255) NULL,
	[KODE_KANTOR] [varchar](255) NULL,
	[KODE_SKEMA_TARIF] [varchar](255) NULL,
	[KODE_STATUS] [varchar](255) NULL,
	[MERK] [varchar](255) NULL,
	[NDPBM] [decimal](38, 4) NULL,
	[NETTO] [decimal](38, 4) NULL,
	[NOMOR_AJU_DOK_ASAL] [varchar](255) NULL,
	[NOMOR_DAFTAR_DOK_ASAL] [varchar](255) NULL,
	[POS_TARIF] [varchar](255) NULL,
	[SERI_BAHAN_BAKU] [int] NULL,
	[SERI_BARANG] [int] NULL,
	[SERI_IJIN] [int] NULL,
	[SERI_BARANG_DOK_ASAL] [int] NULL,
	[SPESIFIKASI_LAIN] [varchar](255) NULL,
	[TANGGAL_DAFTAR_DOK_ASAL] [datetime] NULL,
	[TIPE] [varchar](255) NULL,
	[UKURAN] [varchar](255) NULL,
	[URAIAN] [varchar](255) NULL,
	[ID_BARANG] [int] NULL,
	[ID_HEADER] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [CIF]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [CIF_RUPIAH]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [HARGA_PENYERAHAN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [HARGA_PEROLEHAN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [JENIS_SATUAN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [JUMLAH_SATUAN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [KODE_ASAL_BAHAN_BAKU]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [KODE_BARANG]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [KODE_FASILITAS_DOKUMEN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [KODE_JENIS_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [KODE_KANTOR]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [KODE_SKEMA_TARIF]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [KODE_STATUS]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [MERK]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [NDPBM]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [NETTO]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [NOMOR_AJU_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [NOMOR_DAFTAR_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [POS_TARIF]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [SERI_BAHAN_BAKU]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [SERI_BARANG]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [SERI_IJIN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [SERI_BARANG_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [SPESIFIKASI_LAIN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [TANGGAL_DAFTAR_DOK_ASAL]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [TIPE]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [UKURAN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [URAIAN]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [ID_BARANG]
GO
ALTER TABLE [Bea_Cukai_Bahan_Baku] ADD  DEFAULT (NULL) FOR [ID_HEADER]
GO
