SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Lokasi_Bayar](
	[ID] [int] NOT NULL,
	[KODE_LOKASI_BAYAR] [varchar](255) NULL,
	[URAIAN_LOKASI_BAYAR] [varchar](255) NULL
) ON [PRIMARY]
GO
