SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Pembayar](
	[ID] [int] NOT NULL,
	[KODE_PEMBAYAR] [varchar](255) NULL,
	[URAIAN_PEMBAYAR] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Bea_Cukai_Pembayar] ADD  DEFAULT (NULL) FOR [KODE_PEMBAYAR]
GO
ALTER TABLE [Bea_Cukai_Pembayar] ADD  DEFAULT (NULL) FOR [URAIAN_PEMBAYAR]
GO
