SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_TPB_Barang](
	[ID] [int] NULL,
	[ASURANSI] [decimal](38, 2) NULL,
	[CIF] [decimal](38, 2) NULL,
	[CIF_RUPIAH] [decimal](38, 2) NULL,
	[DISKON] [decimal](38, 2) NULL,
	[FLAG_KENDARAAN] [varchar](255) NULL,
	[FOB] [decimal](38, 2) NULL,
	[FREIGHT] [decimal](38, 2) NULL,
	[HARGA_BARANG_LDP] [decimal](38, 2) NULL,
	[HARGA_INVOICE] [decimal](38, 2) NULL,
	[HARGA_PENYERAHAN] [decimal](38, 2) NULL,
	[HARGA_SATUAN] [decimal](38, 2) NULL,
	[JENIS_KENDARAAN] [decimal](38, 2) NULL,
	[JUMLAH_BAHAN_BAKU] [int] NULL,
	[JUMLAH_KEMASAN] [int] NULL,
	[JUMLAH_SATUAN] [decimal](38, 4) NULL,
	[KAPASITAS_SILINDER] [decimal](38, 2) NULL,
	[KATEGORI_BARANG] [varchar](255) NULL,
	[KODE_ASAL_BARANG] [varchar](255) NULL,
	[KODE_BARANG] [varchar](255) NULL,
	[KODE_FASILITAS_DOKUMEN] [varchar](255) NULL,
	[KODE_GUNA] [varchar](255) NULL,
	[KODE_JENIS_NILAI] [varchar](255) NULL,
	[KODE_KEMASAN] [varchar](255) NULL,
	[KODE_LEBIH_DARI4TAHUN] [varchar](255) NULL,
	[KODE_NEGARA_ASAL] [varchar](255) NULL,
	[KODE_SATUAN] [varchar](255) NULL,
	[KODE_SKEMA_TARIF] [varchar](255) NULL,
	[KODE_STATUS] [varchar](255) NULL,
	[KONDISI_BARANG] [varchar](255) NULL,
	[MERK] [varchar](255) NULL,
	[NETTO] [decimal](38, 4) NULL,
	[NILAI_INCOTERM] [decimal](38, 4) NULL,
	[NILAI_PABEAN] [decimal](38, 2) NULL,
	[NOMOR_MESIN] [varchar](255) NULL,
	[NOMOR_RANGKA] [varchar](255) NULL,
	[POS_TARIF] [varchar](255) NULL,
	[SERI_BARANG] [int] NULL,
	[SERI_IJIN] [int] NULL,
	[SERI_POS_TARIF] [int] NULL,
	[SPESIFIKASI_LAIN] [varchar](255) NULL,
	[TAHUN_PEMBUATAN] [datetime] NULL,
	[TIPE] [varchar](255) NULL,
	[UKURAN] [varchar](255) NULL,
	[URAIAN] [varchar](500) NULL,
	[VOLUME] [decimal](38, 4) NULL,
	[ID_HEADER] [int] NULL,
	[ID_EKSPORTIR] [varchar](255) NULL,
	[NAMA_EKSPORTIR] [varchar](255) NULL,
	[ALAMAT_EKSPORTIR] [varchar](255) NULL,
	[KODE_PERHITUNGAN] [varchar](255) NULL,
	[SERI_BARANG_DOK_ASAL] [int] NULL,
	[NO_PENGAJUAN] [varchar](50) NULL
) ON [PRIMARY]
GO
