SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [POType_Cls](
	[POType_Cls] [varchar](15) NOT NULL,
	[Description] [varchar](35) NULL,
	[last_Update] [datetime] NULL,
	[Last_User] [varchar](15) NULL,
	[Register_User] [datetime] NULL,
 CONSTRAINT [PK_POType_Cls] PRIMARY KEY CLUSTERED 
(
	[POType_Cls] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
