SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[JENIS_TARIF] [varchar](255) NULL,
	[JUMLAH_SATUAN] [decimal](38, 4) NULL,
	[KODE_ASAL_BAHAN_BAKU] [int] NULL,
	[KODE_FASILITAS] [varchar](255) NULL,
	[KODE_KOMODITI_CUKAI] [varchar](255) NULL,
	[KODE_SATUAN] [varchar](255) NULL,
	[KODE_TARIF] [varchar](255) NULL,
	[NILAI_BAYAR] [decimal](38, 2) NULL,
	[NILAI_FASILITAS] [decimal](38, 2) NULL,
	[NILAI_SUDAH_DILUNASI] [decimal](38, 2) NULL,
	[SERI_BAHAN_BAKU] [int] NULL,
	[SERI_BARANG] [int] NULL,
	[TARIF] [decimal](38, 2) NULL,
	[TARIF_FASILITAS] [decimal](38, 2) NULL,
	[ID_BAHAN_BAKU] [int] NULL,
	[ID_BARANG] [int] NULL,
	[ID_HEADER] [int] NULL,
	[NO_PENGAJUAN] [varchar](50) NULL,
 CONSTRAINT [PK__Bea_Cuka__3214EC278A2298A8] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__JENIS__640EA3F6]  DEFAULT (NULL) FOR [JENIS_TARIF]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__JUMLA__6502C82F]  DEFAULT (NULL) FOR [JUMLAH_SATUAN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___65F6EC68]  DEFAULT (NULL) FOR [KODE_ASAL_BAHAN_BAKU]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___66EB10A1]  DEFAULT (NULL) FOR [KODE_FASILITAS]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___67DF34DA]  DEFAULT (NULL) FOR [KODE_KOMODITI_CUKAI]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___68D35913]  DEFAULT (NULL) FOR [KODE_SATUAN]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__KODE___69C77D4C]  DEFAULT (NULL) FOR [KODE_TARIF]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__NILAI__6ABBA185]  DEFAULT (NULL) FOR [NILAI_BAYAR]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__NILAI__6BAFC5BE]  DEFAULT (NULL) FOR [NILAI_FASILITAS]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__NILAI__6CA3E9F7]  DEFAULT (NULL) FOR [NILAI_SUDAH_DILUNASI]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__SERI___6D980E30]  DEFAULT (NULL) FOR [SERI_BAHAN_BAKU]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__SERI___6E8C3269]  DEFAULT (NULL) FOR [SERI_BARANG]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__TARIF__6F8056A2]  DEFAULT (NULL) FOR [TARIF]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__TARIF__70747ADB]  DEFAULT (NULL) FOR [TARIF_FASILITAS]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__ID_BA__71689F14]  DEFAULT (NULL) FOR [ID_BAHAN_BAKU]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__ID_BA__725CC34D]  DEFAULT (NULL) FOR [ID_BARANG]
GO
ALTER TABLE [Bea_Cukai_TPB_Bahan_Baku_Tarif] ADD  CONSTRAINT [DF__Bea_Cukai__ID_HE__7350E786]  DEFAULT (NULL) FOR [ID_HEADER]
GO
