SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Bea_Cukai_Tipe_Kontainer](
	[ID] [int] NOT NULL,
	[KODE_TIPE_KONTAINER] [varchar](255) NULL,
	[URAIAN_TIPE_KONTAINER] [varchar](255) NULL
) ON [PRIMARY]
GO
