SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [IQC_SamplingPlan](
	[SamplingID] [int] IDENTITY(1,1) NOT NULL,
	[MaterialCode] [varchar](50) NOT NULL,
	[LotSize] [int] NOT NULL,
	[SampleSize] [int] NOT NULL,
	[AQL_Level] [varchar](20) NULL,
	[Accept] [int] NULL,
	[Reject] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SamplingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
